events {}
http {
    server {
        listen 11434;
        location / {
            proxy_pass https://104.18.38.236;
            proxy_set_header Host api.groq.com;
            proxy_ssl_server_name on;
            proxy_ssl_name api.groq.com;
        }
    }
}
